# Generated by Django 4.2.7 on 2025-12-29 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscriptionplan_usersubscription_savedrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='delivery_tracking_available',
            field=models.BooleanField(default=False, verbose_name='Доступен трекинг доставки'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='installment_available',
            field=models.BooleanField(default=False, verbose_name='Доступна рассрочка (после 5 заказов)'),
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('bank', models.CharField(max_length=255, verbose_name='Банк')),
                ('account', models.CharField(max_length=50, verbose_name='Расчетный счет')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('orders_count', models.IntegerField(default=0, verbose_name='Количество заказов')),
                ('installment_available', models.BooleanField(default=False, verbose_name='Доступна рассрочка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Компания пользователя',
                'verbose_name_plural': 'Компании пользователей',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'inn')},
            },
        ),
    ]
