# Generated by Django 4.2.7 on 2025-12-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='parsing_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфигурация парсинга'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='parsing_method',
            field=models.CharField(blank=True, choices=[('EXCEL', 'Excel парсинг'), ('CSV', 'CSV парсинг'), ('PDF', 'PDF парсинг'), ('WEB_SCRAPING', 'Веб-скрапинг'), ('API', 'API интеграция'), ('MANUAL', 'Ручной ввод')], max_length=20, null=True, verbose_name='Метод парсинга'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обработан'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='products_count',
            field=models.IntegerField(default=0, verbose_name='Количество товаров'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='default_parsing_method',
            field=models.CharField(choices=[('EXCEL', 'Excel парсинг'), ('CSV', 'CSV парсинг'), ('PDF', 'PDF парсинг'), ('WEB_SCRAPING', 'Веб-скрапинг'), ('API', 'API интеграция'), ('MANUAL', 'Ручной ввод')], default='EXCEL', max_length=20, verbose_name='Метод парсинга по умолчанию'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='parsing_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфигурация парсинга'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, verbose_name='Веб-сайт'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'Обрабатывается'), ('PROCESSED', 'Обработан'), ('FAILED', 'Ошибка')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
