"""Add delivery tracking models

Revision ID: e2e8081136bf
Revises: 57afd9bbb3f0
Create Date: 2025-11-07 16:59:53.497743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e8081136bf'
down_revision = '57afd9bbb3f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SHIPPED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_delivery_tracking_id'), 'delivery_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_tracking_status'), 'delivery_tracking', ['status'], unique=False)
    op.create_table('delivery_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SHIPPED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tracking_id'], ['delivery_tracking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_events_id'), 'delivery_events', ['id'], unique=False)
    op.create_index(op.f('ix_delivery_events_occurred_at'), 'delivery_events', ['occurred_at'], unique=False)
    op.add_column('orders', sa.Column('estimated_delivery_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'estimated_delivery_date')
    op.drop_index(op.f('ix_delivery_events_occurred_at'), table_name='delivery_events')
    op.drop_index(op.f('ix_delivery_events_id'), table_name='delivery_events')
    op.drop_table('delivery_events')
    op.drop_index(op.f('ix_delivery_tracking_status'), table_name='delivery_tracking')
    op.drop_index(op.f('ix_delivery_tracking_id'), table_name='delivery_tracking')
    op.drop_table('delivery_tracking')
    # ### end Alembic commands ###

