# Generated by Django 4.2.7 on 2025-12-03 08:55

from django.db import migrations, models
from datetime import datetime


def generate_order_numbers(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.filter(order_number__isnull=True):
        # Генерируем номер заявки в формате O031225-1
        date_str = order.created_at.strftime('%d%m%y')  # ДДММГГ
        
        # Находим максимальный номер заявки за этот день
        same_day_orders = Order.objects.filter(
            created_at__date=order.created_at.date(),
            order_number__isnull=False,
            order_number__startswith=f'O{date_str}-'
        )
        
        if same_day_orders.exists():
            max_num = 0
            for o in same_day_orders:
                try:
                    num_part = int(o.order_number.split('-')[1])
                    max_num = max(max_num, num_part)
                except (ValueError, IndexError):
                    pass
            order_num = max_num + 1
        else:
            order_num = 1
        
        order.order_number = f'O{date_str}-{order_num}'
        order.save(update_fields=['order_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер заявки'),
        ),
        migrations.RunPython(generate_order_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True, null=True, verbose_name='Номер заявки'),
        ),
    ]
