# Generated by Django 4.2.7 on 2025-12-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='installment',
            field=models.BooleanField(default=False, verbose_name='Оформлено в рассрочку'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_company_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID компании пользователя'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Номер счета')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/', verbose_name='PDF файл')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='invoices/excel/', verbose_name='Excel файл')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Заказ принят'), ('COLLECTED', 'Собран'), ('IN_TRANSIT', 'Передан в доставку'), ('ON_THE_WAY', 'В пути'), ('DELIVERED', 'Доставлен')], default='ACCEPTED', max_length=20, verbose_name='Статус')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем (м³)')),
                ('items_count', models.IntegerField(default=0, verbose_name='Количество позиций')),
                ('status_history', models.JSONField(default=list, verbose_name='История статусов')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='orders.order', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Трекинг доставки',
                'verbose_name_plural': 'Трекинг доставок',
                'ordering': ['-updated_at'],
            },
        ),
    ]
