# Generated by Django 4.2.7 on 2025-12-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_installment_order_user_company_id_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytracking',
            name='confirmation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tracking/confirmation/', verbose_name='Фото подтверждения'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='current_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Текущая широта'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='current_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Текущая долгота'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя водителя'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон водителя'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='eta_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='ETA (минуты)'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Трекинг активен'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='loading_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tracking/loading/', verbose_name='Фото загрузки'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='unloading_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tracking/unloading/', verbose_name='Фото выгрузки'),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер автомобиля'),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_DRIVER', 'Ожидание водителя'), ('DRIVER_ASSIGNED', 'Водитель назначен'), ('ON_THE_WAY_TO_PICKUP', 'Едет к складу'), ('ARRIVED_AT_PICKUP', 'Прибыл на склад'), ('LOADED', 'Загружен'), ('ON_THE_WAY_TO_DESTINATION', 'В пути к получателю'), ('DELIVERED_PENDING_CONFIRM', 'Доставлен (ожидает подтверждения)'), ('COMPLETED', 'Завершён')], default='WAITING_FOR_DRIVER', max_length=30, verbose_name='Статус'),
        ),
    ]
