# Generated by Django 4.2.7 on 2025-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_add_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytracking',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_DRIVER', 'Ожидание водителя'), ('DRIVER_ASSIGNED', 'Водитель назначен'), ('WAITING_FOR_LOADING', 'Ожидает погрузки'), ('ON_THE_WAY_TO_PICKUP', 'Едет к складу'), ('ARRIVED_AT_PICKUP', 'Прибыл на склад'), ('LOADED', 'Загружен'), ('ON_THE_WAY_TO_DESTINATION', 'В пути к получателю'), ('DELIVERED_PENDING_CONFIRM', 'Доставлен (ожидает подтверждения)'), ('COMPLETED', 'Завершён')], default='WAITING_FOR_DRIVER', max_length=30, verbose_name='Статус'),
        ),
    ]
