# Generated by Django 4.2.7 on 2025-12-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('article', models.CharField(db_index=True, max_length=100, verbose_name='Артикул')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Наценка (%)')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'indexes': [models.Index(fields=['article'], name='catalog_pro_article_42a28f_idx'), models.Index(fields=['is_active'], name='catalog_pro_is_acti_14fc6b_idx')],
            },
        ),
    ]
