# Generated by Django 4.2.7 on 2025-12-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(choices=[('РФ', 'РФ'), ('Китай', 'Китай'), ('КР', 'КР'), ('РК', 'РК')], default='РФ', max_length=20, verbose_name='Происхождение'),
        ),
    ]
