# Generated by Django 4.2.7 on 2025-12-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promotional',
            field=models.BooleanField(default=False, verbose_name='Акционный'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
    ]
