# Generated by Django 4.2.7 on 2025-12-03 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_pricelist_parsing_config_pricelist_parsing_method_and_more'),
        ('catalog', '0003_product_is_promotional_product_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
    ]
