# Generated by Django 4.2.7 on 2025-12-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_markup_som'),
        ('catalog', '0004_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_products', to='suppliers.pricelist', verbose_name='Прайс-лист'),
        ),
    ]
