# Generated by Django 4.2.7 on 2025-12-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_pricelist_parsing_config_pricelist_parsing_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='markup_som',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наценка (сом)'),
        ),
    ]
