# Generated by Django 4.2.7 on 2025-12-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В обработке'), ('COLLECTED', 'Собрана'), ('IN_DELIVERY', 'В доставке'), ('DELIVERED', 'Доставлена'), ('PROBLEMATIC', 'Проблемная'), ('CANCELLED', 'Отменена')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
